# Generated by Django 5.0.2 on 2024-04-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookclass_picture_categoryclass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclass',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books/media/uploads'),
        ),
    ]
