# Generated by Django 5.0.2 on 2024-04-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookclass_picture'),
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingclass',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.bookclass'),
        ),
    ]
